---
title: "Homework 2"
output:
  html_document:
    df_print: paged
---

```{r}
rm(list = ls())

ChicagoLink="https://github.com/Spatial-Data-Analytics-2025/Homework2/raw/refs/heads/main/chicago_spatial_data.gpkg"
library(sf)
st_layers(ChicagoLink)
```
```{r}
gpklink='chicago_spatial_data.gpkg'
```

```{r}
library(sf)

fuel_stations = read_sf(gpklink, layer = "fuel_stations")
schools = read_sf(gpklink, layer = "schools")
good_buffers = read_sf(gpklink, layer = "good_buffers")
good_centers = read_sf(gpklink, layer = "good_centers")
relocate_points = read_sf(gpklink, layer = "relocate_points")
good_routes = read_sf(gpklink, layer = "good_routes")

```

```{r}
library(ggplot2)

# Fuel stations

fuel_gg = ggplot() +
theme_bw() +
geom_sf(data = fuel_stations, color = 'black') +
ggtitle("Fuel Stations")
fuel_gg
saveRDS(fuel_gg, file='fuel_stations.rds')

# Schools

school_gg = ggplot() +
theme_bw() +
geom_sf(data = schools, color = 'green') +
ggtitle("Schools")
school_gg
saveRDS(school_gg, file='schools.rds')

# Good buffers

buffers_gg = ggplot() +
theme_bw() +
geom_sf(data = good_buffers, fill = NA, color = 'red') +
ggtitle("Good Buffers")
buffers_gg
saveRDS(buffers_gg, file='good_buffers.rds')

# Good centers

centers_gg = ggplot() +
theme_bw() +
geom_sf(data = good_centers, color = 'red', size = 2) +
ggtitle("Good Centers")
centers_gg
saveRDS(centers_gg, file='good_centers.rds')

# Relocate points

relocate_gg = ggplot() +
theme_bw() +
geom_sf(data = relocate_points, color = 'magenta', size = 2, shape = 4) +
ggtitle("Stations to Relocate")
relocate_gg
saveRDS(relocate_gg, file='relocate_points.rds')

# Good routes

routes_gg = ggplot() +
theme_bw() +
geom_sf(data = good_routes, color = 'yellow') +
ggtitle("Good Routes for Gas")
routes_gg
saveRDS(routes_gg, file='good_routes.rds')

```
```{r}
library(ggplot2)
library(sf)

# Combined map
map_relocate = ggplot() +
  geom_sf(data = good_buffers, fill = NA, color = "red", size = 2) +     
  geom_sf(data = good_centers, color = "red", size = 2, shape = 5) +        
  geom_sf(data = fuel_stations, color = "black", size = 1) +                
  geom_sf(data = schools, color = "green", size = .8) +                      
  geom_sf(data = relocate_points, color = "magenta", size = 3, shape = 4) +
  geom_sf(data = good_routes, color = "yellow", size = 4) +                  
  theme_bw() +
  ggtitle("Map of Stations to Relocate")

# Show the map
map_relocate

# Save for dashboard
saveRDS(map_relocate, file = "map_of_stations_to_relocate.rds")



```

```{r}
install.packages("mapview")
library(mapview)
library(sf)
library(dplyr)


gpklink <- "chicago_spatial_data.gpkg"
relocate_points <- read_sf(gpklink, layer = "relocate_points")
schools <- read_sf(gpklink, layer = "schools")
relocate_points <- st_transform(relocate_points, 4326)
schools <- st_transform(schools, 4326)

buffer_75m <- st_buffer(relocate_points, dist = 75)

nearby_schools <- st_intersection(schools, buffer_75m)

mapview(buffer_75m, color = "red", alpha = 0.2, legend = FALSE) +
  mapview(nearby_schools, color = "yellow", legend = FALSE) +
  mapview(relocate_points, color = "red", cex = 2, layer.name = "Relocate Points")


```

